stages:
    - build
    - publish
build:
    stage: build
    image: node:18-bullseye
    tags: &b_runner
        - builder
        - docker-executor
    script:
        - yarn install
        - yarn build
    artifacts:
        expire_in: 1 week
        paths:
            - dist
npm:
    stage: publish
    only:
        - master
    tags: *b_runner
    script:
        - npm publish --access public
    when: on_success
